# Основной
TOKEN = "6172385271:AAHYeTps9AXE8dP77_JM4kXV0kIPm22WFwM"

# тестовый
# TOKEN = "911710144:AAGmHGL80xy_dlQPhx-LxqivNSNQDHrGEjw"

# Основной
TOKENC = "303078994:AAFJHY1df6bRv8VtXxzxHoajhVmlHz3cyeY"

# Тестовый
# TOKENC = "5750687344:AAG-AGZjwyLKInDj4LNMQTR7KxH_QpDlUsQ"

ActiveUser = {}

# РУСКИЙ ЯЗЫК КНОПКИ И СООБЩЕНИЯ
ru = {
    "omporindivid": "Как вы хотите зарегистрироваться",
    "bcompany": "Организация",
    "bindivid": "Частное лицо",
    "entername": "Как Вас зовут (фамилия имя).",
    "enterinn": "Укажите ИНН Вашей организации.",
    "enterpinfl": "Укажите Ваш ПИНФЛ",
    "entercname": "Укажите наименование Вашей организации",
    "enteradr": "Укажите Адрес, или отправьте локацию.",
    "enterphone": "Укажите контактный телефон для связи",
    "enterperson": "Укажите имя контактного лица.",
    "confirm": "Подтвердите информацию",
    "entertask": "Опишите Вашу проблему. Если есть какая либо дополнительная информация или контакт, пожалуйста укажите их тоже",
    "enterreview": "Опишите ваше предложение, отзыв или жалобу",
    "rating": "Поставьте вашу оценку.",
    "restart": "Перезапустить",
    "mainmenu": "Главное меню",
    "newtask": "Новая заявка",
    "mytasks": "Мои заявки",
    "review": "Отзыв/жалоба",
    "rate": "Оценка",
    "settings": "Настройки",
    "showmydata": "Мои данные",
    "changemydata": "Изменить мои данные",
    "suport": "Техническая поддержка",
    "qtochange": "Что вы хотите изменить?",
    "bcname": "Наименование организации",
    "bmyname": "Мое имя",
    "binn": "ИНН",
    "bpinfl": "ПИНФЛ",
    "badr": "Адрес",
    "bphone": "Контактный телефон",
    "bperson": "Контактное лицо",
    "breg": "Регистрация",
    "errorcom": "Не верная команда",
    "bsend": "Отправить",
    "welcome": "Здравствуйте! Чем я могу помочь",
    "hi": "Я могу принять Вашу заявку и направить ее мастеру. Или прринять от вас отзыв, пожелание или жалобу.",
    "by": "Да",
    "bn": "Нет",
    "lngsel": "Пожалуйста выберите язык",
    "enteragayn": "Пожалуйста введите все данные повторно. \n Выберите язык",
    "sname": "Имя:",
    "scname": "Наименование оррганизации:",
    "sperson": "Контактное лицо:",
    "sadr": "Адрес:",
    "sphone": "Телефон:",
    "slang": "Язык:",
    "success": "Операция успешнь выполнена.",
    "searchnone": "По Вашему запросу ничего нет.",
    "contractifno": "Укажите номер долгосрочного договора если он есть. Если нет нажмите ппропустить.",
    "bskip": "Пропустить",
    "bsave": "Сохранить",
    "blang": "Язык",
    "bcancel": "Отмена",
    "selectlang": 'Выберите язык'
}

# АНГЛИЙСКИЙ ЯЗЫК КНОПКИ И СООБЩЕНИЯ
en = {
    "omporindivid": "How do you want to register",
    "bcompany": "Organization",
    "bindivid": "Individual",
    "entername": "What is your name (last name, first name).",
    "enterinn": "Enter your organization's TIN.",
    "enterpinfl": "Enter your PINFL.",
    "entercname": "Enter your organization name.",
    "enteradr": "Enter address, or send location.",
    "enterphone": "Enter contact phone number.",
    "enterperson": "Enter contact person name.",
    "confirm": "Confirm information",
    "entertask": "Describe your problem. If there is any additional information or contact, please also indicate them.",
    "enterreview": "Describe your suggestion, feedback or complaint.",
    "rating": "Rate your experience.",
    "restart": "Restart",
    "mainmenu": "Main menu",
    "newtask": "New request",
    "mytasks": "My requests",
    "review": "Feedback/Complaint",
    "rate": "Rating",
    "settings": "Settings",
    "showmydata": "My data",
    "changemydata": "Change my data",
    "suport": "Technical support",
    "qtochange": "What do you want to change?",
    "bcname": "Organization name",
    "bmyname": "My name",
    "binn": "TIN",
    "bpinfl": "Individual Taxpayer Number",
    "badr": "Address",
    "bphone": "Contact phone",
    "bperson": "Contact person",
    "breg": "Registration",
    "errorcom": "Invalid command",
    "bsend": "Send",
    "welcome": "Hello! How can I help you?",
    "hi": "I can accept your request and send it to the master. Or I can accept your feedback, suggestion or complaint.",
    "by": "Yes",
    "bn": "No",
    "lngsel": "Please select a language",
    "enteragayn": "Please enter all the data again. \n Select a language",
    "sname": "Name:",
    "scname": "Organization name:",
    "sperson": "Contact person:",
    "sadr": "Address:",
    "sphone": "Phone:",
    "slang": "Language:",
    "success": "Operation completed successfully.",
    "searchnone": "There is nothing matching your request.",
    "contractifno": "Enter the long-term contract number if you have one. If not, skip it.",
    "bskip": "Skip",
    "bsave": "Save",
    "blang": "Language",
    "bcancel": "Cancel",
    "selectlang": "Select a language"
}

# УЗБЕКСКИЙ ЯЗЫК КНОПКИ И СООБЩЕНИЯ
uz = {
    "omporindivid": "Siz qaysi holatda ro'yxatdan o'tmoqchisiz",
    "bcompany": "Tashkilot",
    "bindivid": "Shaxsiy",
    "entername": "Ismingizni kiriting (familiya ism).",
    "enterinn": "Tashkilotingizning STIRni kiriting.",
    "enterpinfl": "PINFL-ni kiriting",
    "entercname": "Tashkilotingizning nomini kiriting",
    "enteradr": "Manzilingizni yoki lokatsiyani yuboring.",
    "enterphone": "Aloqa uchun telefon raqamini kiriting",
    "enterperson": "Aloqa uchun shaxsingizning ismini kiriting.",
    "confirm": "Ma'lumotlarni tasdiqlang",
    "entertask": "Muxtlislikingizni ta'riflang. Agar qo'shimcha ma'lumot yoki aloqa bo'lsa, ularni ham ko'rsating",
    "enterreview": "Tavsiyangizni, mulohazangizni yoki shikoyatingizni tasvirlang",
    "rating": "Baholaringizni berishingiz mumkin.",
    "restart": "Qayta boshlash",
    "mainmenu": "Asosiy menyu",
    "newtask": "Yangi so'rov",
    "mytasks": "Mening so'rovlari",
    "review": "Mulohaza / shikoyat",
    "rate": "Baholash",
    "settings": "Sozlamalar",
    "showmydata": "Mening ma'lumotlarim",
    "changemydata": "Ma'lumotlarimni o'zgartirish",
    "suport": "Texnik yordam",
    "qtochange": "Nima o'zgartirmoqchisiz?",
    "bcname": "Tashkilot nomi",
    "bmyname": "Mening ismim",
    "binn": "STIR",
    "bpinfl": "PINFL",
    "badr": "Manzil",
    "bphone": "Bog'lanish uchun telefon",
    "bperson": "Bog'lanish uchun shaxs",
    "breg": "Ro'yxatdan o'tish",
    "errorcom": "Noto'g'ri buyruq",
    "bsend": "Yuborish",
    "welcome": "Salom! Men sizga qanday yordam berishim mumkin?",
    "hi": "Men sizning so'rovingizni qabul qilib ustaga yo'naltirishim mumkin. Yoki sizning, fikringizni yoki shikoyatingizni qabul qilishim mumkin.",
    "by": "Ha",
    "bn": "Yo'q",
    "lngsel": "Iltimos, tilni tanlang",
    "enteragayn": "Iltimos, barcha ma'lumotlarni qaytadan kiriting. \n Tilni tanlang",
    "sname": "Ism:",
    "scname": "Tashkilot nomi:",
    "sperson": "Bog'lanish uchun shaxs:",
    "sadr": "Manzil:",
    "sphone": "Telefon:",
    "slang": "Til:",
    "success": "Amal muvaffaqiyatli bajarildi.",
    "searchnone": "So'rovingiz bo'yicha hech narsa topilmadi.",
    "contractifno": "Shartnomaning raqamini kiriting, agar bo'lmasa (O'tkazib yuborish)-ni bosing.",
    "bskip": "O'tkazib yuborish",
    "bsave": "Saqlash",
    "blang": "Til",
    "bcancel": "Bekor qilish",
    "selectlang": "Tilni tanlang"
}