# Основной
TOKEN = "6172385271:AAHYeTps9AXE8dP77_JM4kXV0kIPm22WFwM"

# тестовый
# TOKEN = "911710144:AAGmHGL80xy_dlQPhx-LxqivNSNQDHrGEjw"

# Основной
# TOKEN = "911710144:AAGmHGL80xy_dlQPhx-LxqivNSNQDHrGEjw"

# Тестовый
TOKENC = "911710144:AAGmHGL80xy_dlQPhx-LxqivNSNQDHrGEjw"

ActiveUser = {}
ru = {
    "omporindivid": "Как вы хотите зарегистрироваться",
    "bcompany": "Организация",
    "bindivid": "Частное лицо",
    "entername": "Как Вас зовут (фамилия имя).",
    "enterinn": "Укажите ИНН Вашей организации.",
    "enterpinfl": "Укажите Ваш ПИНФЛ",
    "entercname": "Укажите наименование Вашей организации",
    "enteradr": "Укажите Адрес.",
    "enterphone": "Укажите контактный телефон для связи",
    "enterperson": "Укажите имя контактного лица.",
    "confirm": "Подтвердите информацию",
    "entertask": "Опишите Вашу проблему. Если есть какая либо дополнительная информация или контакт, пожалуйста укажите их тоже",
    "enterreview": "Опишите ваше предложение, отзыв или жалобу",
    "rating": "Поставьте вашу оценку.",
    "restart": "Перезапустить",
    "mainmenu": "Главное меню",
    "newtask": "Новая заявка",
    "mytasks": "Мои заявки",
    "review": "Отзыв/жалоба",
    "rate": "Оценка",
    "settings": "Настройки",
    "showmydata": "Мои данные",
    "changemydata": "Изменить мои данные",
    "suport": "Техническая поддержка",
    "qtochange": "Что вы хотите изменить?",
    "bcname": "Наименование организации",
    "bmyname": "Мое имя",
    "binn": "ИНН",
    "bpinfl": "ПИНФЛ",
    "badr": "Адрес",
    "bphone": "Контактный телефон",
    "bperson": "Контактное лицо",
    "breg": "Регистрация",
    "errorcom": "Не верная команда",
    "bsend": "Отправить",
    "welcome": "Здравствуйте! Чем я могу помочь",
    "hi": "Я могу принять Вашу заявку и направить ее мастеру. Или прринять от вас отзыв, пожелание или жалобу.",
    "by": "Да",
    "bn": "Нет",
    "lngsel": "Пожалуйста выберите язык",
    "enteragayn": "Пожалуйста введите все данные повторно. \n Выберите язык",
    "sname": "Имя:",
    "scname": "Наименование оррганизации:",
    "sperson": "Контактное лицо:",
    "sadr": "Адрес:",
    "sphone": "Телефон:",
    "slang": "Язык:",
    "success": "Операция успешнь выполнена.",
    "searchnone": "По Вашему запросу ничего нет."
}
en = {
    "omporindivid": "How do you want to register",
    "bcompany": "Organization",
    "bindivid": "Individual",
    "entername": "What's your name (surname, name).",
    "enterinn": "Enter your organization's TIN.",
    "enterpinfl": "Enter your PINFL",
    "entercname": "Enter your organization's name",
    "enteradr": "Enter your address.",
    "enterphone": "Enter a contact phone number.",
    "enterperson": "Enter the name of the contact person.",
    "confirm": "Confirm information",
    "entertask": "Describe your problem. If there is any additional information or contacts, please also specify them.",
    "enterreview": "Describe your suggestion, feedback, or complaint",
    "rating": "Rate your experience.",
    "restart": "Restart",
    "mainmenu": "Main menu",
    "newtask": "New task",
    "mytasks": "My tasks",
    "review": "Feedback/complaint",
    "rate": "Rate",
    "settings": "Settings",
    "showmydata": "My data",
    "changemydata": "Change my data",
    "suport": "Technical support",
    "qtochange": "What do you want to change?",
    "bcname": "Organization name",
    "bmyname": "My name",
    "binn": "TIN",
    "bpinfl": "PINFL",
    "badr": "Address",
    "bphone": "Contact phone",
    "bperson": "Contact person",
    "breg": "Registration",
    "errorcom": "Invalid command",
    "bsend": "Send",
    "welcome": "Hello! How can I help you?",
    "hi": "I can accept your task and forward it to a master. Or accept feedback, suggestion or complaint from you.",
    "by": "Yes",
    "bn": "No",
    "lngsel": "Please select a language",
    "enteragayn": "Please enter all the data again. \n Select a language",
    "sname": "Name:",
    "scname": "Organization name:",
    "sperson": "Contact person:",
    "sadr": "Address:",
    "sphone": "Phone:",
    "slang": "Language:",
    "success": "Operation completed successfully.",
    "searchnone": "No results found for your query."
}
uz = {
    "omporindivid": "Qanday ro'yxatdan o'tmoqchi bo'lishingizni tanlang",
    "bcompany": "Tashkilot",
    "bindivid": "Shaxsiy shaxs",
    "entername": "Ismingizni kiriting (familiya, ism).",
    "enterinn": "Tashkilotingizning INN raqamini kiriting.",
    "enterpinfl": "PINFL raqamingizni kiriting",
    "entercname": "Tashkilotingizning nomini kiriting",
    "enteradr": "Manzilingizni kiriting.",
    "enterphone": "Aloqa uchun kontaktni telefon raqamini kiriting",
    "enterperson": "Kontakt shaxsning ismini kiriting.",
    "confirm": "Ma'lumotni tasdiqlang",
    "entertask": "Muammohingizni ta'riflang. Agar qo'shimcha ma'lumot yoki kontakt mavjud bo'lsa, ularni ham kiritishingiz mumkin",
    "enterreview": "Taklifingizni, fikringizni yoki shikoyatingizni ta'riflang",
    "rating": "Baholaringizni qo'ying.",
    "restart": "Qayta boshlash",
    "mainmenu": "Asosiy menyuga qaytish",
    "newtask": "Yangi ariza",
    "mytasks": "Mening arizalarim",
    "review": "Fikr/shikoya",
    "rate": "Baholash",
    "settings": "Sozlamalar",
    "showmydata": "Mening ma'lumotlarim",
    "changemydata": "Mening ma'lumotlarimni o'zgartirish",
    "suport": "Texnik yordam",
    "qtochange": "Nimani o'zgartirmoqchisiz?",
    "bcname": "Tashkilot nomi",
    "bmyname": "Ismim",
    "binn": "STIR",
    "bpinfl": "PINFL",
    "badr": "Manzil",
    "bphone": "Aloqa telefoni",
    "bperson": "Bog'lanish uchun shaxs",
    "breg": "Ro'yxatdan o'tish",
    "errorcom": "Noto'g'ri buyruq",
    "bsend": "Jo'natish",
    "welcome": "Salom! Sizga qanday yordam berishim mumkin?",
    "hi": "Sizning arizangizni qabul qilish va uztomonga yo'l qo'yishim mumkin. Yoki sizdan taqriz, taklif yoki shikoyat qabul qilishim mumkin.",
    "by": "Ha",
    "bn": "Yo'q",
    "lngsel": "Iltimos, tilni tanlang",
    "enteragayn": "Iltimos, barcha ma'lumotlarni qayta kiriting. \n Tilni tanlang",
    "sname": "Ism:",
    "scname": "Tashkilot nomi:",
    "sperson": "Bog'lanish uchun shaxs:",
    "sadr": "Manzil:",
    "sphone": "Telefon:",
    "slang": "Til:",
    "success": "Operatsiya muvaffaqiyatli bajarildi.",
    "searchnone": "Sizning so'rovingiz uchun hech narsa topilmadi."
}