import telebot, os
from Classes.db import Database


# ==========================================================================
# Основной
TOKEN = "6172385271:AAHYeTps9AXE8dP77_JM4kXV0kIPm22WFwM"

# тестовый
# TOKEN = "911710144:AAGmHGL80xy_dlQPhx-LxqivNSNQDHrGEjw"
# ==========================================================================

# ==========================================================================
# Основной
TOKENC = "303078994:AAFJHY1df6bRv8VtXxzxHoajhVmlHz3cyeY"

# Тестовый
# TOKENC = "5750687344:AAG-AGZjwyLKInDj4LNMQTR7KxH_QpDlUsQ"
# ==========================================================================


ActiveUser = {} # Глобальная переменная для каждого пользователя идентифицируется по ключу ключ - id пользователя
sendedmessages = []
mainclass = None
dbname = os.path.dirname(os.path.abspath(__file__)) + '/Database/' + 'lmtasksbase.db'
db = Database(dbname)
bot = telebot.TeleBot(TOKEN)
users = db.select_table('Users')
for user in users:
    ActiveUser[user[0]] = {'id': user[0]}
    ActiveUser[user[0]]['Pause_main_handler'] = False
    ActiveUser[user[0]]['Finishedop'] = True
    ActiveUser[user[0]]['block_main_menu'] = False
    ActiveUser[user[0]]['block_nt1'] = False

# РУСКИЙ ЯЗЫК КНОПКИ И СООБЩЕНИЯ
ru = {
    "omporindivid": "Как вы хотите зарегистрироваться",
    "bcompany": "🏛 Организация",
    "bindivid": "👤 Частное лицо",
    "entername": "Как Вас зовут (фамилия имя).",
    "enterinn": "Укажите ИНН Вашей организации.",
    "enterpinfl": "Укажите Ваш ПИНФЛ",
    "entercname": "Укажите наименование Вашей организации",
    "enteradr": "Укажите Адрес, или отправьте локацию.",
    "enterphone": "Укажите контактный телефон для связи",
    "enterperson": "Укажите имя контактного лица.",
    "confirm": "Подтвердите информацию",
    "entertask": "Опишите Вашу проблему. Если есть какая либо дополнительная информация или контакт, пожалуйста укажите их тоже",
    "enterreview": "Опишите ваше предложение, отзыв или жалобу",
    "rating": "Поставьте вашу оценку.",
    "restart": "🔄 Перезапустить",
    "mainmenu": "🏠 Главное меню",
    "newtask": "📝 Новая заявка",
    "mytasks": "📋 Мои заявки",
    "review": "🖍 Отзыв/жалоба",
    "rate": "🌟 Оценка",
    "settings": "⚙️ Настройки",
    "showmydata": "🗄 Мои данные",
    "changemydata": "✏️ Изменить мои данные",
    "suport": "Техническая поддержка",
    "qtochange": "Что вы хотите изменить?",
    "bcname": "Наименование организации",
    "bmyname": "Мое имя",
    "binn": "🆔 ИНН",
    "bpinfl": "🆔 ПИНФЛ",
    "badr": "🏘 Адрес",
    "bphone": "📞 Контактный телефон",
    "bperson": "👤 Контактное лицо",
    "breg": "📋 Регистрация",
    "errorcom": "⚠️ Не верная команда",
    "bsend": "📨 Отправить",
    "welcome": "Здравствуйте! Чем я могу помочь",
    "hi": "Я могу принять Вашу заявку и направить ее мастеру. Или прринять от вас отзыв, пожелание или жалобу.",
    "by": "✅ Да",
    "bn": "⛔️ Нет",
    "lngsel": "Пожалуйста выберите язык",
    "enteragayn": "Пожалуйста введите все данные повторно. \n Выберите язык",
    "sname": "Имя:",
    "scname": "Наименование оррганизации:",
    "sperson": "Контактное лицо:",
    "sadr": "Адрес:",
    "sphone": "Телефон:",
    "slang": "Язык:",
    "success": "✅ Операция успешно выполнена.",
    "searchnone": "По Вашему запросу ничего нет.",
    "contractifno": "Укажите номер долгосрочного договора если он есть. Если нет нажмите ппропустить.",
    "bskip": "⏩ Пропустить",
    "bsave": "💾 Сохранить",
    "blang": "🇺🇿🇬🇧🇷🇺 Язык",
    "bcancel": "⛔️ Отмена",
    "selectlang": 'Выберите язык',
    "locleave": "⏩ Пропустить",
    "locadd": "➕ Добавить локацию",
    "locwhere": "Куда должен подъехать мастер? Выберите локацию из списка, добавьте новую или пропустите этот шаг",
    "locsendloc": "Отправьте локацию",
    "locerrorloc": "Вы не отправили локацию.\nПожалуйста отправьте локацию",
    "locentername": "Укажите название для новой локации.\nНапример:\nгГоловной офис или филиал мирабадского района.",
    "setmylocs": "📍 Мои локации",
    "setchange": "✏️ Изменить",
    "setmestochange": "Чтобы изменить локацию нажмите на кнопку [Изменить] под нужной локацией\nВы так же "": можете добавить новую.",
    "setwywtch": "Что вы хотите изменить?",
    "setlocationch": "📍 Локацию",
    "setnameloc": "Название",
    "setdelete": "🗑 Удалить",
    "setconf": "Вы уверены что хотите удалить эту локацию?",
    "setconf2": "Вы не подтвердили удаление.\nУдалить локацию?"
}

# АНГЛИЙСКИЙ ЯЗЫК КНОПКИ И СООБЩЕНИЯ
en = {
    "omporindivid": "How do you want to register",
    "bcompany": "🏛 Organization",
    "bindivid": "👤 Individual",
    "entername": "What is your name (last name, first name).",
    "enterinn": "Enter your organization's TIN.",
    "enterpinfl": "Enter your PINFL.",
    "entercname": "Enter your organization name.",
    "enteradr": "Enter address, or send location.",
    "enterphone": "Enter contact phone number.",
    "enterperson": "Enter contact person name.",
    "confirm": "Confirm information",
    "entertask": "Describe your problem. If there is any additional information or contact, please also indicate them.",
    "enterreview": "Describe your suggestion, feedback or complaint.",
    "rating": "Rate your experience.",
    "restart": "🔄 Restart",
    "mainmenu": "🏠 Main menu",
    "newtask": "📝 New request",
    "mytasks": "📋 My requests",
    "review": "🖍 Feedback/Complaint",
    "rate": "🌟 Rating",
    "settings": "⚙️ Settings",
    "showmydata": "🗄 My data",
    "changemydata": "✏️ Change my data",
    "suport": "Technical support",
    "qtochange": "What do you want to change?",
    "bcname": "Organization name",
    "bmyname": "My name",
    "binn": "🆔 TIN",
    "bpinfl": "🆔 Individual Taxpayer Number",
    "badr": "🏘 Address",
    "bphone": "📞 Contact phone",
    "bperson": "👤 Contact person",
    "breg": "📋 Registration",
    "errorcom": "⚠️ Invalid command",
    "bsend": "📨 Send",
    "welcome": "Hello! How can I help you?",
    "hi": "I can accept your request and send it to the master. Or I can accept your feedback, suggestion or complaint.",
    "by": "✅ Yes",
    "bn": "⛔️ No",
    "lngsel": "Please select a language",
    "enteragayn": "Please enter all the data again. \n Select a language",
    "sname": "Name:",
    "scname": "Organization name:",
    "sperson": "Contact person:",
    "sadr": "Address:",
    "sphone": "Phone:",
    "slang": "Language:",
    "success": "✅ Operation completed successfully.",
    "searchnone": "There is nothing matching your request.",
    "contractifno": "Enter the long-term contract number if you have one. If not, skip it.",
    "bskip": "⏩ Skip",
    "bsave": "💾 Save",
    "blang": "🇺🇿🇬🇧🇷🇺 Language",
    "bcancel": "⛔️ Cancel",
    "selectlang": "Select a language",
    "locleave": "⏩ Skip",
    "locadd": "➕ Add location",
    "locwhere": "Where should the master come? Choose a location from the list, add a new one, or skip this step",
    "locsendloc": "Send location",
    "locerrorloc": "You haven't sent a location.\nPlease send a location",
    "locentername": "Specify a name for the new location.\nFor example:\nMain office or Mirabad district branch.",
    "setmylocs": "📍 My locations",
    "setchange": "✏️ Change",
    "setmestochange": "To change a location, click on the [Change] button below the desired location. You can also add a new one.",
    "setwywtch": "What would you like to change?",
    "setlocationch": "📍 Location",
    "setnameloc": "Name",
    "setdelete": "🗑 Delete",
    "setconf": "Are you sure you want to delete this location?",
    "setconf2": "You haven't confirmed the deletion. Delete the location?"
}

# УЗБЕКСКИЙ ЯЗЫК КНОПКИ И СООБЩЕНИЯ
uz = {
    "omporindivid": "Siz qaysi holatda ro'yxatdan o'tmoqchisiz",
    "bcompany": "🏛 Tashkilot",
    "bindivid": "👤 Shaxsiy",
    "entername": "Ismingizni kiriting (familiya ism).",
    "enterinn": "Tashkilotingizning STIRni kiriting.",
    "enterpinfl": "PINFL-ni kiriting",
    "entercname": "Tashkilotingizning nomini kiriting",
    "enteradr": "Manzilingizni yoki lokatsiyani yuboring.",
    "enterphone": "Aloqa uchun telefon raqamini kiriting",
    "enterperson": "Aloqa uchun shaxsingizning ismini kiriting.",
    "confirm": "Ma'lumotlarni tasdiqlang",
    "entertask": "Muxtlislikingizni ta'riflang. Agar qo'shimcha ma'lumot yoki aloqa bo'lsa, ularni ham ko'rsating",
    "enterreview": "Tavsiyangizni, mulohazangizni yoki shikoyatingizni tasvirlang",
    "rating": "Baholaringizni berishingiz mumkin.",
    "restart": "🔄 Qayta boshlash",
    "mainmenu": "🏠 Asosiy menyu",
    "newtask": "📝 Yangi so'rov",
    "mytasks": "📋 Mening so'rovlari",
    "review": "🖍 Mulohaza/shikoyat",
    "rate": "🌟 Baholash",
    "settings": "⚙️ Sozlamalar",
    "showmydata": "🗄 Mening ma'lumotlarim",
    "changemydata": "✏️ Ma'lumotlarimni o'zgartirish",
    "suport": "Texnik yordam",
    "qtochange": "Nima o'zgartirmoqchisiz?",
    "bcname": "Tashkilot nomi",
    "bmyname": "Mening ismim",
    "binn": "🆔 INN",
    "bpinfl": "🆔 PINFL",
    "badr": "🏘 Manzil",
    "bphone": "📞 Bog'lanish uchun telefon",
    "bperson": "👤 Bog'lanish uchun shaxs",
    "breg": "📋 Ro'yxatdan o'tish",
    "errorcom": "⚠️ Noto'g'ri buyruq",
    "bsend": "📨 Yuborish",
    "welcome": "Salom! Men sizga qanday yordam berishim mumkin?",
    "hi": "Men sizning so'rovingizni qabul qilib ustaga yo'naltirishim mumkin. Yoki sizning, fikringizni yoki shikoyatingizni qabul qilishim mumkin.",
    "by": "✅ Ha",
    "bn": "⛔️ Yo'q",
    "lngsel": "Iltimos, tilni tanlang",
    "enteragayn": "Iltimos, barcha ma'lumotlarni qaytadan kiriting. \n Tilni tanlang",
    "sname": "Ism:",
    "scname": "Tashkilot nomi:",
    "sperson": "Bog'lanish uchun shaxs:",
    "sadr": "Manzil:",
    "sphone": "Telefon:",
    "slang": "Til:",
    "success": "✅ Amal muvaffaqiyatli bajarildi.",
    "searchnone": "So'rovingiz bo'yicha hech narsa topilmadi.",
    "contractifno": "Shartnomaning raqamini kiriting, agar bo'lmasa (O'tkazib yuborish)-ni bosing.",
    "bskip": "⏩ O'tkazib yuborish",
    "bsave": "💾 Saqlash",
    "blang": "🇺🇿🇬🇧🇷🇺 Til",
    "bcancel": "⛔️ Bekor qilish",
    "selectlang": "Tilni tanlang",
    "locleave": "⏩ O'tkazib yuborish",
    "locadd": "➕ Lokatsiya qo'shish",
    "locwhere": "Usta qayerga kelishi kerak? Ro'yxatdan bir lokatsiyani tanlang, yangi qo'shing yoki bu qadamni o'tkazing",
    "locsendloc": "Lokatsiyani yuboring",
    "locerrorloc": "Siz lokatsiyani yubormadingiz.\nIltimos, lokatsiyani yuboring",
    "locentername": "Yangi lokatsiyaga nom berin.\nMisol uchun:\nAsosiy ofis yoki Mirabad tumani filiali.",
    "setmylocs": "Mening joylashuvlarim",
    "setchange": "✏️ O'zgartirish",
    "setmestochange": "Joylashuvni o'zgartirish uchun, talab etilgan joylashuvning pastidagi [O'zgartirish] tugmasini bosing. Siz yangi joylashuvni ham qo'shishingiz mumkin.",
    "setwywtch": "Nima o'zgartirmoqchisiz?",
    "setlocationch": "📍 Joylashuv",
    "setnameloc": "Nomi",
    "setdelete": "🗑 O'chirish",
    "setconf": "Ushbu joylashuvni o'chirishga ishonchingiz komilmi?",
    "setconf2": "O'chirishni tasdiqlamadingiz. Joylashuvni o'chirishni xohlaysizmi?"
}